config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: 'home#index'

  get '/works', to: 'home#works'
  get '/lovers', to: 'home#lovers'
  get '/program', to: 'home#program'
  get '/contact', to: 'home#contact'
  get '/coworker', to: 'home#users_all'

  post '/sendmail', to: 'home#send_mail'

  get '/profil/:id', to: 'home#show', as: 'profil'



  get "/note", to: 'homes#note_user'
  post "/note", to: 'homes#noter'

  get "/part", to: "homes#index"
  get "/project", to: 'homes#project'
  get "/correction", to: 'homes#correction'

  resources :liens, only: [:new, :create, :edit, :update, :destroy]
  resources :students, only: [:new, :create, :show, :edit, :update, :destroy]

end

app/controllers/administrateur_controller.rb
class AdministrateurController < ApplicationController
	before_action:admin

	def admin
		if current_user.try(:admin?)

		else
			redirect_to root_path
		end
	end
	
  	def index
  		@user = User.all
  	end
  	
end

app/helpers/administrateur_helper.rb
module AdministrateurHelper
end

app/views/administrateur/index.html.erb
<style type="text/css">
	
	body {
		margin: 0px;
		padding: 0px;
	}

	.double {
		margin: 5px 40px;
		display: flex;
	}

	.left {
		display: block;
		width: 320px;
		border: 2px solid black;
		border-radius: 10px;
		height: 420px;
		background-color: lightblue;
	}

	li {
		list-style-type: none;
	}

	a {
		text-decoration: none;
		font-size: bold;
	}

</style>

<h1>page administrateur</h1>

<div class="double">
	<div class="left">
		<ul>
			<li><p>DigitalWorker</p></li>
		</ul>
	</div>
	<div class="right">
		<div class="worker">
			<ul>
				<% @user.each do |users| %>
					<li><%= link_to users.username, profil_path(users.id) %> : <%= button_to "effacer", registration_path(users), data: { confirm: "Are you sure?" }, method: :delete %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>