config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: 'home#index'

  get '/works', to: 'home#works'
  get '/lovers', to: 'home#lovers'
  get '/program', to: 'home#program'
  get '/contact', to: 'home#contact'
  get '/coworker', to: 'home#users_all'

  post '/sendmail', to: 'home#send_mail'

  get '/profil/:id', to: 'home#show', as: 'profil'



  get "/note", to: 'homes#note_user'
  post "/note", to: 'homes#noter'

  get "/part", to: "homes#index"
  get "/project", to: 'homes#project'
  get "/correction", to: 'homes#correction'

  resources :liens, only: [:new, :create, :edit, :update, :destroy]
  resources :students, only: [:new, :create, :show, :edit, :update, :destroy]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  before_action :user_signed_in?, only: [:lovers, :program]

    def send_mail
        user = params[:user]
        if UsersMailer.contact(user).deliver_now
          note "message envoyé"
          redirect_to root_path
        else
          note "donné invalid, veuillez reéssayer"
          render "contact"
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def users_all
        @user = User.all
    end

  	def index

  	end

  	def works

  	end

  	def lovers

  	end

  	def contact

  	end

  	def program

  	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  	before_action :logged_in?

  	def index
      @lien = Lien.all
      if Date.current == last_projet_day.tomorrow.tomorrow
        no_admin.each do |k, u|
          if u.noted == false
            if u.note1 + u.note2.to_i < 10
              u.joker = u.joker - 1
            end
            u.noted = true
            u.save!
          end
        end
        @hash = no_admin
      end
  	end

    def correction
      puts "××××××××××××××××××××××××××××#{no_admin.key(Student.find_by(user_id: current_user.id))}"
      if Date.current == last_projet_day.tomorrow
        if Correct.last.nil?
          user_hash = hash2(no_admin.length)
          l = Correct.new(list: user_hash.to_s)
          l.liste = Liste.last
          l.save
          no_admin.each do |k, u|
            u.update(note1: 0, note2: 0, correcteur1: 0, correcteur2: 0, noted1: false, noted2: false, noted: false)
          end
        else
          unless Correct.last.liste_id == Liste.last.id
            no_admin.each do |k, u|
              u.update(note1: 0, note2: 0, correcteur1: 0, correcteur2: 0, noted1: false, noted2: false, noted: false)
            end
            h = no_admin.length
            user_hash = hash2(h.to_i)

            l = Correct.new(list: user_hash.to_s)
            l.liste = Liste.last
            l.save
          else
            user_hash = eval(Correct.last.list)
          end
        end
        unless current_user.try(:admin?)
          @hash = user_hash[no_admin.key(Student.find_by(user_id: current_user.id))]
          (1..5).to_a.each do |c|
            @h = user_hash[c]
            @h.each do |d|
              e = no_admin[d]
              if e.correcteur1 == 0
                e.correcteur1 = c
              elsif e.correcteur1 != 0 && e.correcteur1 != c
                e.correcteur2 = c
              end
              e.save
            end
          end
        else
          @hash = user_hash
        end
      else
        redirect_to part_path, notice: "le jours du correction n'est pas aujourd'hui"
      end
    end

  	def project
      if current_user.try(:admin?)
    		unless (Date.current.to_s == last_projet_day.to_s)
    			projet_date
    		end
        redirect_to part_path, notice: "un projet doit etre rendu aujourd'hui"
      else
        redirect_to part_path, notice: "vous n'avez pas le droit de faire cette action"
      end
  	end

    def note_user
      @user_id = params[:id]
    end

    def noter
      note = params[:user].permit!.to_hash
      if params[:correcteur_id].to_i == current_user.id
        user_hash = eval(Correct.last.list)
        user_hash[no_admin.key(Student.find_by(user_id: current_user.id)).to_i].each do |t|
          a = no_admin[t]
          if no_admin[t].correcteur1.to_i == no_admin.key(Student.find_by(user_id: current_user.id)).to_i && params[:user_id].to_i == t
            a.note1 = note.length
            a.noted1 = true
            a.save!
          elsif no_admin[t].correcteur2.to_i == no_admin.key(Student.find_by(user_id: current_user.id)).to_i && params[:user_id].to_i == t
            a.note2 = note.length
            a.noted2 = true
            a.save!
          end
          a.save!
        end
        redirect_to correction_path(id: current_user.id), notice: "votre note a été bien pris en compte, Merci!!!"
      else
        flash.now[:notice] = "un petit bug, veuillez reessayer"
        render :note_user
      end
    end
  	
end

app/helpers/home_helper.rb
module HomeHelper

	def note(msg)
		flash[:notice] = msg
	end

	def logged_in?
		if user_signed_in?

		else
			note "vous n'etes pas connecté"
			redirect_to login_path
		end
	end

end

app/helpers/homes_helper.rb
module HomesHelper

	def projet_date
		Liste.create(lejour: Date.current.to_s)
	end

	def last_projet_day
		return Liste.last ? Liste.last.lejour.to_date : "2016-01-01".to_date
	end

	def date_valid?
		#((Date.current.day == last_projet_day.day) && (Date.current.month == last_projet_day.month) && (Date.current.year == last_projet_day.year )) ? true : false
		Date.current == last_projet_day ? true : false
	end

	def correction_date
		Date.current == last_projet_day.tomorrow ? true : false
	end

	def id_random(num)
		return rand(num) + 1
	end

	def hash1(num)
		i = 1
		arr = {}
		while (i <= num) do
			j = id_random(num)
			if !(arr.has_value?(j)) && j != i
				arr[i] = j
				i += 1
			end
		end
		return arr
	end

	def hash2(num)
		x = 0
		l = 1
		arr2 = hash1(num)
		arr1 = {}
		arr = {}
		while ( l <= num) do
			m = id_random(num)
			if !(arr1.has_value?(m)) && (m != l) && (m != arr2[l])
				arr1[l] = m
				arr[l] = [m, arr2[l]]
				l += 1
			end
			x += 1
			break if x == 10000
		end
		hash2(num) if arr.length < num
		return arr
	end

	
    def no_admin
      h = Student.all.order(:id)
      return (1..h.length).zip(h.to_a).to_h
    end

end

app/views/homes/correction.html.erb
<h1>Jour du correction</h1>
<% unless current_user.try(:admin?) %>
<% h = no_admin.key(Student.find_by(user_id: current_user.id)) %>
	<% if Lien.find_by(student_id: no_admin[@hash[0]].id) %>
		<%= Lien.find_by(student_id: no_admin[@hash[0]].id).liengit %> :
		<% if ((no_admin[@hash[0]].correcteur1 == h && no_admin[@hash[0]].noted1 == false) || (no_admin[@hash[0]].correcteur2 == h && no_admin[@hash[0]].noted2 == false)) %>
			<%= link_to "noter", note_path(id: @hash[0]) %>
		<% end %>
	<% else %>
		<p>pas de lien donnee</p>
	<% end %> <br><br>

	<% if Lien.find_by(student_id: no_admin[@hash[1]].id) %>
		<%= Lien.find_by(student_id: no_admin[@hash[1]].id).liengit %> :
		<% if ((no_admin[@hash[1]].correcteur1 == h && no_admin[@hash[1]].noted1 == false) || (no_admin[@hash[1]].correcteur2 == h && no_admin[@hash[1]].noted2 == false)) %>
			<%= link_to "noter", note_path(id: @hash[1]) %>
		<% end %>
	<% else %>
		<p>pas de lien donnee</p>
	<% end %><br><br>
	=> CORRECTEUR => <%= current_user.username %>
<% else %>
	<ul>
	<% @hash.each do |k, v| %>
		<li>
			Etudiant n: <%= v[0] %> : <%= no_admin[v[0]].lastname %> <%= no_admin[v[0]].firstname %> :
				<input type="checkbox" 
					<% if ((no_admin[v[0]].correcteur1 == k && no_admin[v[0]].noted1 == true) || (no_admin[v[0]].correcteur2 == k && no_admin[v[0]].noted2 == true)) %>
						checked="checked"
					<% end %> 
				name="<%= v[0] %>">
			et n: <%= v[1] %> : <%= no_admin[v[1]].lastname %> <%= no_admin[v[1]].firstname %> :
				<input type="checkbox" 
					<% if ((no_admin[v[1]].correcteur1 == k && no_admin[v[1]].noted1 == true) || (no_admin[v[1]].correcteur2 == k && no_admin[v[1]].noted2 == true)) %>
						checked="checked"
					<% end %>
				 name="<%= v[1] %>">
			=> CORRECTEUR => Etudiant n: <%= k %>
		</li>
	<% end %>
	</ul>
<% end %>

app/views/homes/index.html.erb
<h1>ACCUEIL</h1>

<% if Date.current == last_projet_day.tomorrow.tomorrow %>
	<h2>note</h2>
	<p>voici les etudiantes qui ont perdue un joker au correction</p>
	<% 3.times do |t| %>
		<% if t == 0 %>
			<p>ceux qui vont nos quitter</p>
		<% else %>
			<p>ceux qui n'ont plus que <%= t %> joker</p>
		<% end %>
		<% @hash.each do |w, k| %>
			<% if k.joker == t %>
				<li>
					<%= k.username %>
				</li>
			<% end %>
		<% end %>
	<% end %>
	<p>On vous soutient tous, Courage!!!</p>
<% end %>	


<% if (Date.current.day > (last_projet_day.day + 1) && Date.current.month >= last_projet_day.month && Date.current.year >= last_projet_day.year) && current_user.try(:admin?) %>
	<%= link_to "jours de projet", project_path %>
<% end %>

<ul>
	<% Liste.all.each do |k| %>
		<h2>Projet du <%= k.lejour.to_date %></h2>
		<% @lien.each do |l| %>
			<% if l.liste_id == k.id %>
				<li>
					Lien github : <%= l.liengit %> : <%= User.find(Student.find(l.student_id).user_id).username %> : <%= if ((Student.find(l.student_id).user_id == current_user.id) && (l.liste.lejour.to_date == Date.current)) then link_to "editer", edit_lien_path(l.id) end %>
				</li>
			<% end %>
		<% end %>
	<% end %>
</ul>


<% unless current_user.try(:admin?) %>
	<% if date_valid? && !Lien.find_by(student_id: Student.find_by(user_id: current_user.id).id, liste_id: Liste.last) %>
		<%= link_to "lien github", new_lien_path %>
	<% else %>
		<mark>Ooouuuups!!! desolée. Le temps est ecoulé</mark>
	<% end %>
	<br><br>
<% end %>
<% if correction_date %>
	<%= link_to "jours de correction", correction_path %>
<% else %>
	<mark>Bah... C'est pas encore le jours de correction non!!!</mark>
<% end %>

app/views/homes/note_user.html.erb
<h1>noter un etudiant</h1>

<form action="/note" method="post">
	<input type="hidden" name="authenticity_token" value="authenticity_token_key">
	<input type="hidden" name="user_id" value=<%= @user_id %> >
	<input type="hidden" name="correcteur_id" value=<%= current_user.id %> >
	<fieldset>
		<legend>A propos</legend>
		<input type="checkbox" name="user[note_1]"/>
		<label for="user[note_1]">Est-ce que le projet marche bien?</label><br>

		<input type="checkbox" name="user[note_2]"/>
		<label for="user[note_2]">Est-ce que le projet repond au problèmatique dans énnoncé?</label><br>

		<input type="checkbox" name="user[note_3]"/>
		<label for="user[note_3]">Le "readme" est bien fait</label><br>
	</fieldset>
	<fieldset>
		<legend>Le code</legend>
		<input type="checkbox" name="user[note_4]"/>
		<label for="user[note_4]">est)ce qu'il y a trop de repetition des bloc de code</label><br>

		<input type="checkbox" name="user[note_5]"/>
		<label for="user[note_5]">lisibilité du code(commentaire, espace et tabulation)</label><br>

		<input type="checkbox" name="user[note_6]"/>
		<label for="user[note_6]">longueur du code(simple et efficace)</label><br>

		<input type="checkbox" name="user[note_7]"/>
		<label for="user[note_7]">code sans ambiguité:</label><br>
	</fieldset>
	<fieldset>
		<legend>Le vue</legend>

		<input type="checkbox" name="user[note_8]"/>
		<label for="user[note_8]">presentation du vue</label><br>

		<input type="checkbox" name="user[note_9]"/>
		<label for="user[note_9]">fautes de francais</label><br>

		<input type="checkbox" name="user[note_10]"/>
		<label for="user[note_10]">Regle d'ecriture du language</label><br>
			
	</fieldset>
	<input type="submit" value="envoyer">
</form>