config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  root to: 'home#index'

  get '/works', to: 'home#works'
  get '/lovers', to: 'home#lovers'
  get '/program', to: 'home#program'
  get '/contact', to: 'home#contact'
  get '/coworker', to: 'home#users_all'

  post '/sendmail', to: 'home#send_mail'

  get '/profil/:id', to: 'home#show', as: 'profil'



  get "/note", to: 'homes#note_user'
  post "/note", to: 'homes#noter'

  get "/part", to: "homes#index"
  get "/project", to: 'homes#project'
  get "/correction", to: 'homes#correction'

  resources :liens, only: [:new, :create, :edit, :update, :destroy]
  resources :students, only: [:new, :create, :show, :edit, :update, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
	<p>All Right Reserved</p>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to "Contact", contact_path %>
	<%= link_to "how it works", works_path %>
	<% if current_user.try(:admin?) %>
		
		<%= link_to 'gere', rails_admin_path %>	
	<% end %>
	<% if user_signed_in? %>
		<% unless current_user.try(:admin?) %>
			<%= link_to "Digital Workers", coworker_path %>
			<% if s = Student.find_by(user_id: current_user.id) %>
				<%= link_to "profil etudiant", student_path(s.id) %>
				<%= link_to "pour les eleves", part_path %>
			<% else %>
				<%= link_to "devenir etudiant", new_student_path %>	
			<% end %>
		<% else %>
			<%= link_to "pour les eleves", part_path %>
		<% end %>
		<%= link_to "SaynaLover", lovers_path %>
		<%= link_to "Programme", program_path %>
		<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
		<%= current_user.email %>
	<% else %>
		<%= link_to 'Sign In', new_user_session_path %>
		<%= link_to 'Sign Up', new_user_registration_path %>
	<% end %>			
<header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SAYNA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>